FROM python:3.11-slim

WORKDIR /app

COPY jobs/producer/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY jobs/producer/ /app/

ENV PYTHONUNBUFFERED=1

CMD ["python", "generator.py"]
