FROM python:3.11-slim

WORKDIR /app

COPY jobs/consumer/lakehouse/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY jobs/consumer/lakehouse/ /app/

ENV PYTHONUNBUFFERED=1

CMD ["python", "lake_writer.py"]
